### PR TITLE
persist list of watched trips

### PR DESCRIPTION
**Pull request by derhuerst**
- [x] implementation
- [x] basic local testing
- [x] readme
- [x] large-scale testing (with worker on a different machine?)

### CODE REVIEW

**Comment by derhuerst** [comment]
@juliuste Could you try this out? You can run the example code in `example`, and check if proper data is being written. Using `DEBUG='hafas-find-trips:*'`, you can find out if the work-stealing of the queue works.

**Comment by juliuste** [comment]
I probably need redis to test this, right?

**Comment by derhuerst** [comment]
> I probably need redis to test this, right?

Yes. Please let me know which parts the documentation is lacking.

I've been testing this in a medium scale, and the trips-to-be-watched list is still not functioning as intended I think. 🤔

**Comment by derhuerst** [comment]
> I've been testing this in a medium scale, and the trips-to-be-watched list is still not functioning as intended I think. 🤔

I'm using an [LRU cache](https://en.wikipedia.org/wiki/Cache_replacement_policies#Least_recently_used_(LRU)) for the list of trip IDs now. Technically, this is not what I actually want, but it seems to be good enough.

@juliuste We can merge this if it works for you and the docs are acceptable.

**Comment by derhuerst** [comment]
The queue being used (`bullmq`) seems to be a bit buggy unfortunately, but this is somewhat out of scope of this PR.

**Comment by derhuerst** [comment]
The trips LRU cache with a hardcoded maximum capacity is not optimal yet, because usually you don‘t know the expected maximum nr of trips in the bounding box up front, will have to change that.

**Pull request merged**
